version: '3.8'

services:
  opstack-bridge-indexer:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./database:/usr/src/app/database
    restart: unless-stopped